DELIMITER $$

DROP PROCEDURE IF EXISTS `universidad`.`PCR_ALUMNOS_RECURSANTES` $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `PCR_ALUMNOS_RECURSANTES`()
BEGIN


CREATE TEMPORARY TABLE ALUMNOS_NO_REGULARIZADOS
SELECT ID_ALUMNO, ID_ASIGNATURA FROM INSCRIPCIONES
WHERE ESTADO = 3;

CREATE TEMPORARY TABLE ALUMNOS_INSCRIPTOS
SELECT ID_ALUMNO, ID_ASIGNATURA FROM INSCRIPCIONES
WHERE ESTADO = 1;


SELECT CONCAT(A.NOMBRE, ' ', A.APELLIDO) ALUMNO, ASIG.DESCRIPCION, 'RECURSANTE' AS ESTADO
FROM ALUMNOS_INSCRIPTOS AI
INNER JOIN ALUMNOS A ON A.ID = AI.ID_ALUMNO
INNER JOIN ASIGNATURAS ASIG ON ASIG.ID = AI.ID_ASIGNATURA
WHERE ID_ALUMNO IN (SELECT ID_ALUMNO FROM ALUMNOS_NO_REGULARIZADOS);


END $$

DELIMITER ;